language: r
cache: packages
sudo: false
r: release
dist: trusty
warnings_are_errors: true
r_check_args: --no-tests --as-cran --no-manual

env:
  - NOT_CRAN=true

apt_packages:
  - libgsl0-dev

r_packages:
  - gsl
  - R.rsp
  - covr

after_success:
  - travis_wait 60 Rscript -e 'covr::codecov()'
